# This file is generated by nvimx. Do not edit by hand.
{
  inputs = {
    lazy-nvim = {
      url = "github:folke/lazy.nvim";
      flake = false;
    };
    blink-cmp = {
      url = "github:saghen/blink.cmp/refs/tags/v1.10.2";
      flake = false;
    };
    bufferline-nvim = {
      url = "github:akinsho/bufferline.nvim/refs/tags/v4.9.1";
      flake = false;
    };
    catppuccin = {
      url = "github:catppuccin/nvim";
      flake = false;
    };
    friendly-snippets = {
      url = "github:rafamadriz/friendly-snippets";
      flake = false;
    };
    gitsigns-nvim = {
      url = "github:lewis6991/gitsigns.nvim";
      flake = false;
    };
    go-nvim = {
      url = "github:ray-x/go.nvim";
      flake = false;
    };
    guihua-lua = {
      url = "github:ray-x/guihua.lua";
      flake = false;
    };
    lazygit-nvim = {
      url = "github:kdheepak/lazygit.nvim";
      flake = false;
    };
    mini-pairs = {
      url = "github:nvim-mini/mini.pairs";
      flake = false;
    };
    mini-surround = {
      url = "github:nvim-mini/mini.surround";
      flake = false;
    };
    noice-nvim = {
      url = "github:folke/noice.nvim";
      flake = false;
    };
    nui-nvim = {
      url = "github:muniftanjim/nui.nvim";
      flake = false;
    };
    nvim-lspconfig = {
      url = "github:neovim/nvim-lspconfig";
      flake = false;
    };
    nvim-notify = {
      url = "github:rcarriga/nvim-notify";
      flake = false;
    };
    nvim-treesitter = {
      url = "github:nvim-treesitter/nvim-treesitter";
      flake = false;
    };
    nvim-web-devicons = {
      url = "github:nvim-tree/nvim-web-devicons";
      flake = false;
    };
    oil-nvim = {
      url = "github:stevearc/oil.nvim";
      flake = false;
    };
    snacks-nvim = {
      url = "github:folke/snacks.nvim";
      flake = false;
    };
  };
  outputs = _: { };
}
